name: family_social
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: ^2.3.3+1
  path: ^1.9.0
  sqflite_common_ffi: ^2.0.0+1
  path_provider: ^2.1.3
  firebase_core: ^2.5.0
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.17.4
  sign_in_button: ^3.2.0
  universal_io: ^2.0.4
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  random_string: ^2.3.1
  fluttertoast: ^8.2.6
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cupertino_icons: ^1.0.2

 
 
